### ISSUE TITLE
ArgumentError: wrong number of arguments (0 for 1) in 'reload'

### ISSUE THREAD

**Issue by inspire22** [notahat/machinist#44]
I keep getting this error.  As far as I can tell its just calling object.reload.  I don't define 'reload' anywhere, so I don't know why it could be saying it needs an argument?

ree-1.8.7-2010.02 > t = Topic.make
making user user0003
making user user0004
ArgumentError: wrong number of arguments (0 for 1)
    from /Users/inspire/.rvm/gems/ree-1.8.7-2010.02/gems/machinist-2.0.0.beta2/lib/machinist/active_record/blueprint.rb:8:in `reload'
    from /Users/inspire/.rvm/gems/ree-1.8.7-2010.02/gems/machinist-2.0.0.beta2/lib/machinist/active_record/blueprint.rb:33:in`value'
    from /Users/inspire/.rvm/gems/ree-1.8.7-2010.02/gems/machinist-2.0.0.beta2/lib/machinist/active_record/blueprint.rb:33:in `outside_transaction'
    from /Users/inspire/.rvm/gems/ree-1.8.7-2010.02/gems/machinist-2.0.0.beta2/lib/machinist/shop.rb:43:in`buy'
    from /Users/inspire/.rvm/gems/ree-1.8.7-2010.02/gems/machinist-2.0.0.beta2/lib/machinist/machinable.rb:55:in `make!'
    from /Users/inspire/.rvm/gems/ree-1.8.7-2010.02/gems/machinist-2.0.0.beta2/lib/machinist/machinable.rb:94:in`decode_args_to_make'
    from /Users/inspire/.rvm/gems/ree-1.8.7-2010.02/gems/machinist-2.0.0.beta2/lib/machinist/machinable.rb:53:in `make!'
    from ./spec/blueprints.rb:43
    from /Users/inspire/.rvm/gems/ree-1.8.7-2010.02/gems/machinist-2.0.0.beta2/lib/machinist/active_record/lathe.rb:8:in`make_one_value'
    from /Users/inspire/.rvm/gems/ree-1.8.7-2010.02/gems/machinist-2.0.0.beta2/lib/machinist/lathe.rb:46:in `make_attribute'
    from /Users/inspire/.rvm/gems/ree-1.8.7-2010.02/gems/machinist-2.0.0.beta2/lib/machinist/lathe.rb:30:in`method_missing'
    from ./spec/blueprints.rb:43
    from /Users/inspire/.rvm/gems/ree-1.8.7-2010.02/gems/machinist-2.0.0.beta2/lib/machinist/blueprint.rb:26:in `instance_eval'
    from /Users/inspire/.rvm/gems/ree-1.8.7-2010.02/gems/machinist-2.0.0.beta2/lib/machinist/blueprint.rb:26:in`make'
    from /Users/inspire/.rvm/gems/ree-1.8.7-2010.02/gems/machinist-2.0.0.beta2/lib/machinist/machinable.rb:39:in `make'
    from /Users/inspire/.rvm/gems/ree-1.8.7-2010.02/gems/machinist-2.0.0.beta2/lib/machinist/machinable.rb:94:in`decode_args_to_make'
    from /Users/inspire/.rvm/gems/ree-1.8.7-2010.02/gems/machinist-2.0.0.beta2/lib/machinist/machinable.rb:38:in `make'
    from (irb):17ree-1.8.7-2010.02 > 
ree-1.8.7-2010.02 >

**Comment by inspire22** [comment]
This was because of the validation-reflections gem - just having it in the gemfile messed up object.reload for some objects.  I'll add an issue with their github!

Rails really needs a way of echoing what gemfiles are loading as plugins/etc.
