### ISSUE TITLE
reload kills blueprints (rails 3, ruby 1.9.2, machinist 1.0.6)

### ISSUE THREAD

**Issue by davidlee** [notahat/machinist#82]
please excuse me if i've neglected to find a duplicate issue, but this looks fresh to me.

```
require './spec/support/blueprints'
 => nil 
ruby-1.9.2-p0 > User.make.class.to_s
 => "User" 
ruby-1.9.2-p0 > reload!
Reloading...
 => true 
ruby-1.9.2-p0 > User.make.class.to_s
RuntimeError: No blueprint for class User
    from /Users/davidlee/.rvm/gems/ruby-1.9.2-p0@global/gems/machinist-1.0.6/lib/machinist.rb:14:in `run'
    from /Users/davidlee/.rvm/gems/ruby-1.9.2-p0@global/gems/machinist-1.0.6/lib/machinist/active_record.rb:53:in `make'
    from (irb):16
    from /Users/davidlee/.rvm/gems/ruby-1.9.2-p0@global/gems/railties-3.0.4/lib/rails/commands/console.rb:44:in `start'
    from /Users/davidlee/.rvm/gems/ruby-1.9.2-p0@global/gems/railties-3.0.4/lib/rails/commands/console.rb:8:in `start'
    from /Users/davidlee/.rvm/gems/ruby-1.9.2-p0@global/gems/railties-3.0.4/lib/rails/commands.rb:23:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'
ruby-1.9.2-p0 > require './spec/support/blueprints'
 => nil 
ruby-1.9.2-p0 > User.make.class.to_s
RuntimeError: No blueprint for class User
    from /Users/davidlee/.rvm/gems/ruby-1.9.2-p0@global/gems/machinist-1.0.6/lib/machinist.rb:14:in `run'
    from /Users/davidlee/.rvm/gems/ruby-1.9.2-p0@global/gems/machinist-1.0.6/lib/machinist/active_record.rb:53:in `make'
    from (irb):18
    from /Users/davidlee/.rvm/gems/ruby-1.9.2-p0@global/gems/railties-3.0.4/lib/rails/commands/console.rb:44:in `start'
    from /Users/davidlee/.rvm/gems/ruby-1.9.2-p0@global/gems/railties-3.0.4/lib/rails/commands/console.rb:8:in `start'
    from /Users/davidlee/.rvm/gems/ruby-1.9.2-p0@global/gems/railties-3.0.4/lib/rails/commands.rb:23:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'
ruby-1.9.2-p0 > load File.expand_path('./spec/support/blueprints.rb')
 => nil 
ruby-1.9.2-p0 > User.make.class.to_s
 => "User" 
```

**Comment by davidlee** [comment]
2.0.0.beta2 is the same

**Comment by notahat** [comment]
This is expected. reload! clears out and reloads all Machinist's classes, so all the blueprint information gets lost.

I'm open to bright ideas for preventing this, but I don't have any.
