### ISSUE TITLE
Uninitialized constant

### ISSUE THREAD

**Issue by ramontayag** [notahat/machinist#91]
On Rails 3.0.9 I get this error when I run features:

```
uninitialized constant Account (NameError)
/Users/dev/Dev/hitracks2/features/support/../../spec/support/blueprints.rb:3
/Users/dev/Dev/hitracks2/features/support/env.rb:7:in `require'
/Users/dev/Dev/hitracks2/features/support/env.rb:7
/Users/dev/.rvm/gems/ree-1.8.7-2011.03@hitracks2/gems/cucumber-1.0.2/bin/../lib/cucumber/rb_support/rb_language.rb:143:in `load'
/Users/dev/.rvm/gems/ree-1.8.7-2011.03@hitracks2/gems/cucumber-1.0.2/bin/../lib/cucumber/rb_support/rb_language.rb:143:in `load_code_file'
/Users/dev/.rvm/gems/ree-1.8.7-2011.03@hitracks2/gems/cucumber-1.0.2/bin/../lib/cucumber/runtime/support_code.rb:176:in `load_file'
/Users/dev/.rvm/gems/ree-1.8.7-2011.03@hitracks2/gems/cucumber-1.0.2/bin/../lib/cucumber/runtime/support_code.rb:78:in `load_files!'
/Users/dev/.rvm/gems/ree-1.8.7-2011.03@hitracks2/gems/cucumber-1.0.2/bin/../lib/cucumber/runtime/support_code.rb:77:in `each'
/Users/dev/.rvm/gems/ree-1.8.7-2011.03@hitracks2/gems/cucumber-1.0.2/bin/../lib/cucumber/runtime/support_code.rb:77:in `load_files!'
/Users/dev/.rvm/gems/ree-1.8.7-2011.03@hitracks2/gems/cucumber-1.0.2/bin/../lib/cucumber/runtime.rb:137:in `load_step_definitions'
/Users/dev/.rvm/gems/ree-1.8.7-2011.03@hitracks2/gems/cucumber-1.0.2/bin/../lib/cucumber/runtime.rb:39:in `run!'
/Users/dev/.rvm/gems/ree-1.8.7-2011.03@hitracks2/gems/cucumber-1.0.2/bin/../lib/cucumber/cli/main.rb:43:in `execute!'
/Users/dev/.rvm/gems/ree-1.8.7-2011.03@hitracks2/gems/cucumber-1.0.2/bin/../lib/cucumber/cli/main.rb:20:in `execute'
/Users/dev/.rvm/gems/ree-1.8.7-2011.03@hitracks2/gems/cucumber-1.0.2/bin/cucumber:14
/Users/dev/.rvm/gems/ree-1.8.7-2011.03@hitracks2/bin/cucumber:19:in `load'
/Users/dev/.rvm/gems/ree-1.8.7-2011.03@hitracks2/bin/cucumber:19
```

And my `spec/support/blueprints.rb`:

```
require 'machinist/active_record'

Account.blueprint do
end
```

**Comment by ramontayag** [comment]
It was my mistake. Sorry!
